import { NextSeo } from 'next-seo';
import Home from '../containers';

function HomePage(): JSX.Element {
  return (
    <>
      <NextSeo title="Create Next App" description="Generated by create next app" />
      <Home />
    </>
  );
}

export default HomePage;
