import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { NextSeo } from 'next-seo';
import Test from '@/containers/test';

function TestPage(): JSX.Element {
  return (
    <>
      <NextSeo title="Create Next App" description="Generated by create next app" />
      <Test />
    </>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export default TestPage;
